name: pet_mart
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  provider: ^6.0.1
  intl: ^0.17.0
  logger: any
  dio: ^4.0.1
  http: any
  firebase_messaging: ^11.1.0
  carousel_slider: ^4.0.0
  font_awesome_flutter: any
  shared_preferences: ^2.0.8
  sticky_and_expandable_list: ^1.0.2
  flutter_progress_dialog: ^0.1.0
  configurable_expansion_tile: ^1.0.0
  flutter_widget_from_html: ^0.8.1+1
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.0.0+2
  device_info: ^2.0.3
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar: ^4.0.2
  easy_dialog: ^1.1.0
  container_tab_indicator: ^0.3.0
  url_launcher: ^6.0.12
  get_it: ^7.2.0
  equatable: ^2.0.3
  #  flutter_open_whatsapp: ^0.1.2
  device_information: ^0.0.4
  rflutter_alert: ^2.0.4
  flutter_dropdown: ^1.0.0+hotfix.1
  ndialog: ^4.1.0
  unique_identifier: ^0.2.2
  pin_code_fields: ^7.3.0
  shape_of_view: ^1.0.2
  back_button_interceptor: ^5.0.2
  timer_count_down: ^2.2.0
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.13.0
  share: ^2.0.4
  flutter_cache_manager: ^3.1.3
  grouped_list: ^4.1.0
  image_picker: ^0.8.5+3
  my_fatoorah: ^3.0.6
  flutter_webview_plugin:
    git: https://github.com/nuc134r/flutter_webview_plugin.git
  group_radio_button: ^1.1.0
  firebase_core: ^1.10.0
  firebase_database: ^8.1.0
  overlay_support: ^1.2.1
  flutter_local_notifications: ^9.0.3
  fluttertoast: ^8.0.8
  video_player: ^2.2.6
  rating_bar: ^0.2.0
  sweetalert: ^0.0.1
  pinch_zoom_image_last: ^0.4.1
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.6
  images_picker: ^1.2.11
  youtube_player_flutter: ^8.0.0
  auto_orientation: ^2.2.1

  chewie: ^1.3.1
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  flutter_app_badger: ^1.3.0










  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"

flutter_launcher_name:
  name: "Pet Mart"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - lang/ar.json
    - lang/en.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages